export type LegalSection = {
  id: string;
  title: string;
  paragraphs: string[];
};

export type LegalDocument = {
  lastModified: string;
  preamble: string[];
  sections: LegalSection[];
};

export const privacyPolicy: LegalDocument = {
  lastModified: '12/30/2025',
  preamble: [
    'Privacy Policy',
    'SelarAI Privacy PolicyLast Modified: [12/30/2025]PLEASE READ THESE TERMS CAREFULLY.',
    'SelarAI LLC ("SelarAI,” "we,” "us,” or "our") is committed to protecting your privacy. This privacy policy (“Privacy Policy") explains how we collect, use, disclose, and safeguard personal information when you interact with our websites, platforms, mobile applications, and other online services that link to this policy (collectively, the "Services").',
    'This Privacy Policy applies to personal information that we collect and process in connection with your use of the Services. It does not apply to third-party websites, services, or applications, even if they are accessible through the Services.',
    'Unless otherwise defined in this Privacy Policy, capitalized terms have the meanings given to them in our Terms of Service (“Terms). In the event of any inconsistency between this Privacy Policy and the Terms regarding definitions or interpretation, the Terms will control.',
  ],
  sections: [
    {
      id: 'what-information-we-collect-about-you',
      title: 'WHAT INFORMATION WE COLLECT ABOUT YOU',
      paragraphs: [
        'Information You Provide to SelarAI. When you interact with us by using the Services or contacting Support, we collect personal information that you provide directly. This includes your login credentials such as your name, email address, password, and single sign-on (SSO) details, as well as user preferences, voice recordings and transcripts, and banking or payment information needed to process transactions. We may also collect other personal data you submit, including information provided when you upload content, request customer support, or participate in marketing promotions. In addition, our mobile applications may request access to your device’s camera, microphone, or photo library in order to support certain features, such as uploading documents or media. We only access this content when you choose to engage with these features. You may control or revoke these permissions through your device settings at any time.',
        'Information We Collect When You Use Our Services. In addition to the information you provide directly, we also collect certain data automatically when you interact with the Services. This includes technical, usage, and device-related information that helps us operate, secure, and improve our platform. The types of data we collect in this context include the following:',
        'Log Files. When you use our Services, we may automatically collect information about your computer hardware and software. This information can include your IP address, browser type, domain names, internet service provider (ISP), the files viewed on our site (e.g., HTML pages, graphics, etc.), operating system, clickstream data, access times and referring website addresses.',
        'Usage Data. We may collect Usage Data when you interact with the Services. Usage Data includes information such as technical logs, performance metrics, device identifiers, system events, and metadata associated with your interactions, including how often certain features are used, when specific actions are triggered, and what parts of the Services you engage with most. We may use third-party service providers to help collect and analyze Usage Data, but we only share it in a de-identified form that does not reveal Your Content. We use this data to support analytics, improve system performance, troubleshoot issues, and optimize the Services.',
        'Information from Cookies and Similar Technologies. We and our third-party partners may collect personal information using cookies, pixel tags, or similar technologies. For more information on our use of cookies and your choices regarding cookies, please see Section 6 (Cookies). We may also collect information through other methods, such as online conferences, events, or contests.',
        'Location and Device Information. When you use the Services via a mobile device, we may collect and process information about your device and real-time location, including GPS coordinates, device type, mobile operating system, unique device identifiers, mobile network information, and diagnostic data. We use this information to enable location-based features (such as contextual recommendations), enhance security, and improve app functionality. You can disable location access through your device settings, but this may limit certain functionalities of the Services.',
      ],
    },
    {
      id: 'how-we-use-personal-data',
      title: 'HOW WE USE PERSONAL DATA',
      paragraphs: [
        'To Provide the Services. We use your account information and Your Content to provide the products and services to you. For example, we use the username and password you choose to provide when signing up for the Services to create your user account. We may also use this information to authenticate you when you use the Services and to provide customer support. We collect the content, communications and other information you provide when you use our Services, including when you initiate the use of the Services, create or share content, and message or communicate with others.',
        'To Improve and Develop Our Product and Services. We use Usage Data to understand how users interact with the Services and to guide product development. This includes identifying popular features, assessing user behavior trends, and evaluating potential new features or integrations. We may also analyze aggregated data across our user base to understand overall usage patterns. When shared externally, this statistical information does not identify individual users.',
        '2.3To Secure and Protect our Users. We use your information to help prevent security incidents, verify accounts, process product sign-ups, and detect misuse of the Services. Log files may also be used to generate general usage statistics, improve navigation, and support compliance with analytics, export control, and regulatory requirements. We collect and log IP addresses to monitor access patterns, investigate security events, and troubleshoot issues. Where appropriate, we may link this automatically collected data to other personal information you provide.',
        '2.4To Communicate with Our Users. We use your account information to communicate with you, which could include providing you with updates and other information relating to our services and products, providing information that you request, and responding to comments, questions, and requests. You may opt out of receiving promotional emails or text messages from SelarAI by following the unsubscribe instructions included in those emails or text messages. If you are unable to do so, please refrain from interacting with promotional materials until an official contact channel is established. If you opt out, we may still send you transactional or relationship messages, such as emails about your account or updates to our products and services. With your permission, we may send you push notifications or in-app messages related to your account activity or promotional content. You can opt out of promotional messages at any time by contacting SelarAI support through the app or your device notification preferences. Transactional messages may still be sent to ensure proper service delivery.',
        '2.5To Monitor and Improve Autonomous System Behavior. We may also use interaction data and system metadata to monitor and improve the autonomous functions of the Services. This includes analyzing agent behavior, error patterns, system-triggered actions, and user overrides in order to support safe deployment, performance tuning, and continuous improvement of agentic capabilities.',
      ],
    },
    {
      id: 'how-we-share-personal-data',
      title: 'HOW WE SHARE PERSONAL DATA',
      paragraphs: [
        'Service Providers. We may share Personal Data with our third-party service providers to support our Services. For example, we may use service providers for data hosting, payment processing, and application development. We may need to share your information with service providers to provide services to you. Examples may include analyzing data or performing statistical analysis on your use of the Services, supplementing the information you provide us in order to provide you with better service, developing and improving the product and services, and providing customer service or support. These service providers are prohibited from using your Personal Data except for these purposes, and they are required to maintain the confidentiality of your information.',
        'Compelled Disclosure. We reserve the right to use or disclose your Personal Data if required by law or if we reasonably believe that use or disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or comply with a law, court order, or legal process. For more details on how your inputs and the outputs generated by the Services are processed, stored, and used, please refer to the “Your Content and AI Output” section of our Terms.',
      ],
    },
    {
      id: 'how-we-transfer-personal-data-internationally',
      title: 'HOW WE TRANSFER PERSONAL DATA INTERNATIONALLY',
      paragraphs: [
        '4.1Scope of International Transfers. As of the date this Privacy Policy was last modified, SelarAI only conducts business within the United States. However, in the event that we share Personal Data of individuals in the EEA, Switzerland or UK with third parties in the future, we will comply with all applicable international laws to safeguard the transfer. We will update this Privacy Policy accordingly if our business operations expand internationally. Please contact us if you need more information about which legal mechanisms we rely on to transfer personal data internationally.',
      ],
    },
    {
      id: 'how-we-store-and-secure-personal-data',
      title: 'HOW WE STORE AND SECURE PERSONAL DATA',
      paragraphs: [
        'Data Storage and Security. We use a variety of security technologies and procedures to help protect your Personal Data from unauthorized access, use or disclosure. We secure the Personal Data you provide on computer servers in a controlled, secure environment, protected from unauthorized access, use or disclosure. All Personal Data is protected using appropriate physical, technical and organizational measures.',
        'Retention of Personal Data. We retain Personal Data that you provide to us where we have an ongoing legitimate business need to do so (for example, as needed to comply with our legal obligations, resolve disputes and enforce our agreements).',
      ],
    },
    {
      id: 'cookies',
      title: 'COOKIES',
      paragraphs: [
        '6.1Cookies. Technologies such as cookies may be used by SelarAI and our analytics or service providers (as applicable). Cookies are used to remember you and to collect information about how you interact with the Services. If you have an account with the Services, we may link this usage data with other information. You may have the option to either accept or refuse these cookies. If you choose to refuse, you may not be able to use some portions of the Services.',
        '6.2What Are Cookies? Cookies are small text files sent to your browser when you visit a website. They allow the site to recognize your device and remember your preferences on future visits. Cookies may store settings or other data to support functionality and improve your experience. Cookies set by us are called first-party cookies, while cookies set by other parties, such as analytics or content providers, are called third-party cookies. These may track activity across multiple websites. We also use third-party mobile analytics tools to understand how users interact with our app, identify bugs or crashes, and improve performance. These tools collect anonymized data such as usage patterns, device status, and error logs, and are not used to personally identify users.',
        '6.3Why Do We Use Cookies? We use first party and third party cookies for several reasons. Some cookies are required for technical reasons in order for our website to operate, and we refer to these as "essential" or "strictly necessary" cookies. Other cookies also enable us to track and target the interests of our users to enhance the experience on our Services. This data is used to analyze trends, administer the website, monitor how visitors navigate around the website, and to gather demographic information about our user base as a whole.',
        '6.4What Types of Cookies Do We Use and How Do We Use Them? We use several types of cookies to support and improve our website. Essential cookies are required to deliver the services available through the site. Performance and functionality cookies enhance the user experience but are not strictly necessary for the website to function. We also use analytics and customization cookies, which help us understand how users interact with the site and allow us to tailor content based on those interactions. These cookies may operate in aggregate form or be used to personalize your experience.',
        '6.5How Can I Control Cookies? You have the right to choose whether to accept or reject cookies. You can manage your cookie preferences through browser settings or by using opt-out links provided by advertising networks. Most browsers allow you to block or delete cookies, although doing so may limit access to certain features on our website. For browser-specific guidance, consult your browser’s help menu. You can also opt out of targeted advertising by visiting aboutads.info/choices, optout.aboutads.info, or, if located in the European Union, youronlinechoices.eu. Please note that opting out of targeted ads does not stop all advertising—it only affects personalized ads.',
      ],
    },
    {
      id: 'your-privacy-rights-and-choices',
      title: 'YOUR PRIVACY RIGHTS AND CHOICES',
      paragraphs: [
        'Access, Correction or Deletion. You can request access, correction, updates or deletion of your Personal Data.',
        'Objection. You can object to our processing of your Personal Data, ask us to restrict processing of your Personal Data or request portability of your Personal Data.',
        'Withdraw Consent. If we have collected and processed your Personal Data with your consent, then you can withdraw your consent at any time. Withdrawing your consent will not affect the lawfulness of any processing we conducted prior to your withdrawal, nor will it affect processing of your Personal Data conducted in reliance on lawful processing grounds other than consent.',
        'Complaint. You have the right to complain to a data protection authority about our collection and use of your Personal Data. To exercise any of these rights, please submit a request using any communication method provided through the Services. If no method is available, you may not to use the Services until a contact mechanism is published.',
        'Please note that to protect personal information, we may verify your identity by a method appropriate to the type of request you are making. Depending on where you reside, you may be entitled to empower an “authorized agent” to submit requests on your behalf. We will require authorized agents to confirm their identity and authority, in accordance with applicable laws. We will respond to your request to change, correct, or delete your data within a reasonable timeframe and notify you of the action we have taken. In some instances, your rights may be limited, such as where fulfilling your request would impair the rights of others, our ability to provide a service you have requested, or our ability to comply with our legal obligations and enforce our legal rights.',
      ],
    },
    {
      id: 'california-privacy-rights',
      title: 'CALIFORNIA PRIVACY RIGHTS',
      paragraphs: [
        '8.1CCPA Applicability. As SelarAI does not currently meet the thresholds established by the California Consumer Privacy Act (the “CCPA”), the CCPA does not apply to your use of the Services. In the event that SelarAI does meet the thresholds established by the CCPA in the future, this section will be updated accordingly.',
      ],
    },
    {
      id: 'other-important-privacy-information',
      title: 'OTHER IMPORTANT PRIVACY INFORMATION',
      paragraphs: [
        'We Never Sell Personal Data. We will never sell your Personal Data to any third party.',
        'Information About Children. The Services are not intended for or targeted at children under 18, and we do not knowingly or intentionally collect Personal Data about children under 18. If you believe that we have collected Personal Data about a child under 18, please contact us at privacy@selaraillc.com so that we may delete the information.',
        '​',
        '[end privacy policy]',
      ],
    },
  ],
};

export const termsOfService: LegalDocument = {
  lastModified: '12/30/2025',
  preamble: [
    'Terms of Service',
    'SelarAI Terms of Service',
    'Last Modified: [12/30/2025]',
    'PLEASE READ THESE TERMS CAREFULLY.',
    'Welcome to the Terms of Service (the “Terms” or “Agreement”) for the Selara mobile application (the “App”) operated by SelarAI LLC ("SelarAI,” “we,” “us,” or “our”). The App and any content, tools, features, and/or functionality offered on or through the App are collectively referred to as the “Services”.',
    'These Terms govern your access to and use of the Services. Please read these Terms carefully, as they include important information about your rights and responsibilities. By accessing and/or using the Services, you are agreeing to these Terms. If you do not understand or agree to these Terms, please do not use the Services.',
    'SelarAI may update these Terms from time to time. When these changes are made, SelarAI will make a new copy of the Terms available at https://www.selara.app/terms. If you keep using the Services after we update these Terms, we will treat your continued use as your agreement to the changes.',
    'For purposes of these Terms, “you” and “your” means the person or entity using the Services. “Party” or “Parties” refers to one or both of the parties to this agreement, respectively.',
    'DISPUTES ABOUT THESE TERMS AND THE SERVICES ARE SUBJECT TO BINDING ARBITRATION AS SET FORTH IN THE “MANDATORY ARBITRATION AND CLASS ACTION WAIVER” SECTION BELOW.',
  ],
  sections: [
    {
      id: 'using-the-services',
      title: 'USING THE SERVICES',
      paragraphs: [
        'Eligibility. To use the Services, you must be at least eighteen (18) years of age and have the legal capacity to enter into these Terms.',
        'The Services. We provide AI-powered personal assistant services through an application that integrates generative artificial intelligence and agentic software to assist with tasks, actions, and content generation on your device. The Services may produce text, commands, data transformations, or other outputs in response to your input. These outputs are generated by automated systems and are not reviewed by a human prior to delivery. You understand and agree that the outputs may be inaccurate, incomplete, biased, or otherwise flawed, and should not be solely relied upon without independent verification. SelarAI’s models and functionalities may evolve over time through updates or retraining. AI Output (defined below) may vary between sessions or versions. You acknowledge and agree that SelarAI reserves the right to update, modify, or discontinue certain features at any time without liability.',
        'Access Platforms. You may access and use the Services through: (i) our mobile application available on the Apple App Store (the “iOS App”); (ii) our application for MacOS devices (the “Mac App”); or (iii) our mobile application available on the Google Play Store (the “Android App”) (collectively, the “App”), as available. These Terms apply to your use of the Services regardless of access platform. Your use of the App may also be subject to additional terms imposed by the platform provider (e.g., Apple or Google), including their respective terms of service and usage policies. In the event of any conflict between these Terms and the mandatory terms required by the applicable platform provider, such platform terms will control solely to the extent required.',
        'Use. We hereby permit you to use the Services for your personal use, provided that you comply with these Terms. If any software, content, or other materials owned or controlled by us are distributed to you as part of your use of the Services, we hereby grant you a personal, non-assignable, non-sublicensable, non-transferable, and non-exclusive right and license to access and display such software, content, and materials provided to you as part of the Services and right to download the App onto your applicable device for the sole purpose of enabling you to use the Services as permitted by these Terms. You agree to use the Services responsibly and in compliance with applicable laws, regulations, and ethical standards. SelarAI may monitor usage patterns to prevent abuse and may suspend or terminate access in its sole discretion.',
        'Mobile Device Requirements and Platform Terms. You are responsible for providing the mobile device, wireless service plan, internet access, and other equipment necessary to download, install, and use the App. We do not guarantee that the App will be available in any specific geographic location or on all devices. You may receive push notifications, SMS messages, or other alerts through the App. You control these through your device settings or as described in the message. You are solely responsible for any fees, costs, or expenses incurred through your use of the App.',
        '1.6 Apple App Store. If you access or download the App from the Apple App Store, the following additional terms apply: (i) these Terms are between you and SelarAI only; Apple Inc. (“Apple”) is not a party and has no responsibility for the App or its content; (ii) you are granted a non-transferable license to use the App on any Apple-branded device that you own or control, in accordance with the App Store Terms of Service; (iii) Apple has no obligation to provide maintenance or support for the App; (iv) in the event of a failure to conform to any applicable warranty, you may notify Apple, and Apple may refund the purchase price (if any), but Apple has no further warranty obligations; (v) SelarAI is solely responsible for all claims relating to the App, including product liability, failure to comply with legal or regulatory requirements, consumer protection, privacy, and intellectual property infringement; and (vi) you acknowledge that Apple and its subsidiaries are third-party beneficiaries of these Terms and may enforce them as such.',
        '1.7 Google Play Store. If you access or download the App from the Google Play Store, the following additional terms apply: (i) these Terms are between you and SelarAI only; Google LLC (“Google”) is not a party and has no responsibility or liability for the App or its content; (ii) Google has no obligation to provide maintenance or support services for the App; (iii) SelarAI is solely responsible for any warranties and for all claims relating to the App, including product liability, regulatory compliance, consumer protection, and intellectual property infringement; (iv) your use of the App must comply with all applicable Google Play terms of service and policies; (v) if you purchase subscriptions or content via Google Play, those transactions are processed by Google or its payment providers and are subject to Google’s terms, and SelarAI disclaims responsibility for such transactions except as required by law; and (vi) you represent and warrant that you are not located in a U.S. government-embargoed country or on any U.S. government list of prohibited or restricted parties.',
        '1.8 Restrictions. You agree not to, and will not permit others to do any of the following: (i) copy our app or create similar versions based on the Services; (ii) share access to the Services with any third party without our permission; (iii) use the Services on behalf of any third party except as expressly permitted by us; (iv) incorporate the Services into any other software, product, or service offering; (v) interfere with or circumvent any security, performance, or usage-limiting features of the Services; (vi) reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code, structure, or logic of the Services, except as expressly permitted by applicable law and only upon prior written notice; (vii) remove, obscure, or alter any proprietary notices, disclaimers, or branding appearing in the Services; (viii) use the Services for competitive analysis or to develop a competing product or service; (ix) use the Services for or submit prompts designed to generate illegal, harassing, bullying, unethical, disruptive, or lewd, obscene, violent, harmful, threatening, or criminal outputs or purposes; (x) encourage or assist any third party in any of the foregoing activities; or (xi) infringe or violate another party’s intellectual property rights on the application or through use of the Services.',
      ],
    },
    {
      id: 'your-content-and-accounts',
      title: 'YOUR CONTENT AND ACCOUNTS',
      paragraphs: [
        'Privacy Protection. Our Privacy Policy, available at https://www.selara.app/privacy, describes how we collect, use, and protect your personal information. By using the Services, you agree to the practices described in the Privacy Policy.',
        'Your Content and AI Output. You retain all ownership rights in and to: (i) any data, text, files, prompts, instructions, or other content you submit or upload to the Services (“User Input”); and (ii) any output generated by the Services specifically in response to your User Input (“AI Output”) (collectively, “Your Content”). We do not claim ownership of Your Content. You grant us a limited, non-exclusive license to use, store, reproduce, and process Your Content solely to provide and support the Services, comply with law, and as otherwise described in these Terms. You are solely responsible for Your Content and represent and warrant that you have all necessary rights, consents, and authority to submit Your Content and grant the rights described above. We reserve the right to remove any of Your Content from the Services at our discretion, including where it violates these Terms or applicable law.',
        'Usage Data. SelarAI may collect and use data relating to your access, interactions, and usage of the Services, including technical logs, performance metrics, device identifiers, system events, and AI interaction metadata (“Usage Data”). SelarAI owns all rights, title, and interest in and to Usage Data. We may use Usage Data for analytics, troubleshooting, system improvement, and service optimization, provided that it does not include or reveal Your Content in identifiable form.',
        'Model Training and Data Retention. SelarAI does not sell or share Your Content, including User Input or AI Output, with third-party model providers for independent training. We do not use Your Content to retrain our models unless you have expressly authorized us to do so. However, we may retain Your Content as needed to deliver the Services, fulfill your requests, maintain service continuity, or comply with legal obligations. Separately, we collect and retain Usage Data, including logs and metadata generated through your use of the Services. As described in Section 2.3, SelarAI owns all rights in and to Usage Data, which may be used for analytics, performance optimization, and improving the behavior and reliability of our AI systems.',
        'Account Registration and Security. To access the Services, you may be required to create an account. You agree to provide accurate, complete, and up-to-date account information, and to keep your login credentials secure. You are solely responsible for activity on your account. Notify us immediately at privacy@selaraillc.com if you suspect unauthorized access to your account. We may suspend or terminate accounts in our sole discretion.',
        'Third-Party Applications and Integrations. The Services may allow you to connect or use third-party applications, services, or platforms (“Third-Party Integrations”). Your use of any Third-Party Integration is solely governed by the terms and privacy policies of that provider. We do not control, endorse, or assume liability for any Third-Party Integration. Your interactions with such services are at your own risk.',
      ],
    },
    {
      id: 'intellectual-property',
      title: 'INTELLECTUAL PROPERTY',
      paragraphs: [
        'SelarAI Intellectual Property. These Terms grant you a limited right to access and use the Services as provided. Except for rights explicitly granted to you in these Terms, SelarAI and its licensors retain all rights, title, and interest in and to the Services, including all related software, models, algorithms, user interfaces, documentation, and proprietary technologies. You do not acquire any ownership interest or license in the Services or any underlying system, model, or architecture, whether by implication, estoppel, or otherwise. Nothing in these Terms grants you any rights to access or use the source code, model weights, training data, or internal logic of any component of the Services.',
        'Feedback. We welcome any suggestions, ideas, improvements, or recommendations provided by you relating to SelarAI, our Services, or the functionality of our Services (“Feedback”). By submitting any Feedback, you agree that we may use such Feedback without restriction. You hereby assign to us all rights, title, and interest in and to any feedback you submit. Where assignment is not permitted by law, you grant us a non-exclusive, perpetual, irrevocable, worldwide, royalty-free, sublicensable, and transferable license to use, reproduce, modify, distribute, and incorporate your Feedback into the Services or other products without compensation or attribution. We are under no obligation to use or act on any Feedback.',
      ],
    },
    {
      id: 'disclaimer-of-warranties',
      title: 'DISCLAIMER OF WARRANTIES',
      paragraphs: [
        'Disclaimer of Warranties. THE SERVICES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTIES OF ANY KIND, EXPRESS, IMPLIED, OR STATUTORY. TO THE MAXIMUM EXTENT PERMITTED BY LAW, SELARAI SPECIFICALLY DISCLAIMS ALL IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, TITLE, OR QUIET ENJOYMENT.',
        'THE SERVICES USE GENERATIVE ARTIFICIAL INTELLIGENCE TO PRODUCE RESPONSES, CONTENT, AND OUTPUTS BASED ON USER INPUT. YOU UNDERSTAND AND AGREE THAT: (I) SUCH OUTPUTS MAY BE INACCURATE, INCOMPLETE, OFFENSIVE, OR OTHERWISE UNRELIABLE; (II) OUTPUTS ARE GENERATED AUTOMATICALLY AND ARE NOT REVIEWED OR VERIFIED BY A HUMAN; (III) SELARAI MAKES NO REPRESENTATIONS OR GUARANTEES REGARDING THE LEGALITY, APPROPRIATENESS, ORIGINALITY, OR NON-INFRINGEMENT OF ANY AI-GENERATED OUTPUT; AND (IV) YOU USE SUCH OUTPUTS ENTIRELY AT YOUR OWN RISK.',
        'YOU ACKNOWLEDGE THAT NO INFORMATION OR OUTPUT PROVIDED BY THE SERVICES CONSTITUTES LEGAL, MEDICAL, FINANCIAL, OR OTHER PROFESSIONAL ADVICE. SELARAI DOES NOT WARRANT THAT THE SERVICES OR AI OUTPUT WILL BE ERROR-FREE, RELIABLE, OR SUITABLE FOR ANY PARTICULAR PURPOSE, AND YOU ARE SOLELY RESPONSIBLE FOR EVALUATING ANY OUTPUT BEFORE USING IT IN ANY SETTING.',
        'SELARAI MAY MODIFY, SUSPEND, OR UPDATE THE SERVICES, INCLUDING THE UNDERLYING AI MODELS, AT ANY TIME WITHOUT NOTICE. YOU ACKNOWLEDGE THAT RESULTS MAY VARY OVER TIME AND ACROSS SESSIONS.',
        'YOU ACKNOWLEDGE THAT YOU HAVE NOT RELIED ON ANY REPRESENTATIONS OR WARRANTIES NOT EXPRESSLY SET FORTH IN THESE TERMS.',
      ],
    },
    {
      id: 'payment-terms',
      title: 'PAYMENT TERMS',
      paragraphs: [
        'Payment Authorization. You acknowledge and agree that all the payment information you provide to SelarAI is accurate, current, and complete. You represent and warrant that you have the legal right to use the payment method you provide to us or to our payment processor.',
        'You agree to pay the price of subscription plus all applicable taxes (the “Full Payment Amount”) and authorize us or our payment processor to charge your payment method for the Full Payment Amount monthly.',
        'Authorized Payment Methods. You may use any payment method accepted by SelarAI as listed on the Services. We will collect your payment information in order to carry out collection of payment. We may utilize third party payment processors to process payments on our behalf. We do not guarantee the availability of any specific method at any given time and may add, suspend, or remove payment methods at its discretion.',
        'Refunds and Consumer Rights. Except as stated in these Terms, all Full Payment Amounts are final and non-refundable. We are not responsible for providing or processing refunds unless required by law. Notwithstanding the foregoing, certain jurisdictions (including California and New York) may provide consumer rights that apply to you. These Terms do not limit or waive any non-waivable rights you may have under such laws.',
        'Payment Processing. We use Stripe, Inc. (“Stripe”) to provide payment processing services. By submitting payment information through the Services, you agree to be bound by the Stripe Services Agreement, as updated from time to time by Stripe. You authorize us to share the information you provide to us with Stripe as necessary to facilitate payments, comply with applicable law, and operate the Services. Stripe may collect and process personal data in accordance with its own Privacy Policy. We do not control and are not responsible for Stripe’s handling of your information. Your access to payment-enabled features may be suspended or terminated if you violate the Stripe Services Agreement or if Stripe declines to process a transaction. Stripe is solely responsible for the performance and security of its payment services, and any disputes related to those services must be resolved directly with Stripe. In the event of any conflict between these Terms and the Stripe Services Agreement with respect to payment processing, the Stripe Services Agreement will control.',
        'Free and Beta Services. If you receive any Services free of charge (e.g., trial or zero dollar proof of concept) or released as beta, pilot, limited release, non-production, evaluation, or through platform-specific testing programs such as Apple TestFlight (“Beta Features”), you acknowledge and accept that such Services are provided “AS-IS”, without any representations, warranties, support, maintenance, or other obligation of any kind from SelarAI. Beta Features are experimental in nature and may contain errors, defects, or other issues that could cause system failures or data loss. You acknowledge that Beta Features are intended for testing purposes and may not perform at the level of a commercially available service. SelarAI may provide Beta Features to different categories of users (including invited testers, general beta participants, or limited release groups) and may apply different terms, duration limits, or access restrictions to each category in its sole discretion. Unless otherwise mutually agreed in writing or specified in a separate beta testing agreement, beta access may be provided for a limited duration, and SelarAI may terminate your access to, or use of, a free Service or a Beta Feature at any time, which may include permanent deletion of Your Content. By participating in any beta testing program, you agree to provide Feedback regarding your experience, including reporting bugs, errors, and performance issues, in accordance with Section 3.2 of these Terms. Your use of Beta Features through third-party platforms such as Apple TestFlight is also subject to the applicable platform provider\'s terms and policies.',
      ],
    },
    {
      id: 'indemnification',
      title: 'INDEMNIFICATION',
      paragraphs: [
        'Indemnification. You agree to indemnify, defend, and hold harmless SelarAI, its affiliates, and each of their respective officers, directors, employees, contractors, agents, licensors, and representatives from and against any and all claims, demands, actions, proceedings, investigations, liabilities, damages, losses, costs, and expenses (including reasonable attorneys’ fees and penalties imposed by a governmental or regulatory authority) arising out of or relating to: (i) your breach or violation of these Terms; (ii) your use or misuse of the Services, including reliance on or distribution of AI-generated output; (iii) any User Input or other content you submit, upload, or provide through the Services, including any claim that such content infringes, misappropriates, or violates the intellectual property, privacy, or other rights of any third party; (iv) your violation of any applicable law or regulation in connection with your use of the Services; (v) your use of the Services to generate or disseminate prohibited, harmful, or unlawful content (including false, deceptive, infringing, harassing, or unsafe material); or (vi) your use of any third-party integrations, services, or applications accessed through the Services. SelarAI reserves the right to assume the exclusive defense and control of any matter subject to indemnification by you, in which case you agree to cooperate fully with our defense.',
      ],
    },
    {
      id: 'limitation-of-liability',
      title: 'LIMITATION OF LIABILITY',
      paragraphs: [
        'Limitation of Liability. TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL SELARAI, ITS AFFILIATES, OR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, CONTRACTORS, OR REPRESENTATIVES BE LIABLE: (I) FOR ANY AMOUNT EXCEEDING ONE HUNDRED DOLLARS ($100) IN THE AGGREGATE FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE SERVICES; OR (II) FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOST PROFITS, LOST BUSINESS OPPORTUNITIES, LOSS OF GOODWILL, LOSS OF DATA, OR DIMINUTION IN VALUE, WHETHER BASED IN CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE, EVEN IF SELARAI HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR THE REMEDY OTHERWISE FAILS OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS, SO THE ABOVE MAY NOT APPLY TO YOU IN FULL.',
        'Essential Basis for the Bargain. YOU ACKNOWLEDGE AND AGREE THAT THESE LIMITATIONS OF LIABILITY ARE AN ESSENTIAL PART OF THE BASIS OF THE BARGAIN BETWEEN YOU AND SELARAI AND THAT SELARAI WOULD NOT PROVIDE THE SERVICES TO YOU WITHOUT YOUR AGREEMENT TO THESE LIMITATIONS.',
      ],
    },
    {
      id: 'mandatory-arbitration-and-class-action-waiver',
      title: 'MANDATORY ARBITRATION AND CLASS ACTION WAIVER',
      paragraphs: [
        '8.1 Arbitration. If a dispute arises concerning the interpretation of these Terms or the performance of either Party under them, the Parties agree to first attempt resolution through good faith executive-level discussions. Either Party may initiate this process by delivering a written Notice of Dispute. If the Parties are unable to resolve the dispute within ten (10) business days, the matter shall be resolved by binding arbitration pursuant to the Commercial Arbitration Rules of the American Arbitration Association, as modified by this section, and in accordance with the Federal Arbitration Act (Title 9 of the United States Code).',
        'The arbitration shall be administered by the AAA and decided by a panel of three (3) arbitrators. The legal seat of arbitration shall be Wilmington, Delaware, but unless the Parties agree otherwise, the arbitration proceedings (including hearings) shall be conducted remotely by video conference or other virtual means. The arbitration must be initiated within a reasonable time after the dispute arises, and all statutes of limitation that would apply in a judicial proceeding shall apply. The arbitrators’ decision shall be final and binding, and judgment may be entered thereon in any court of competent jurisdiction. No arbitration may include any person or entity not a party to this Agreement without both Parties’ written consent. Each Party waives any right to appeal, review, or vacate the award, except as permitted under the Federal Arbitration Act.',
        'The prevailing Party, as determined by the arbitrators, shall be entitled to recover all costs and fees, including reasonable attorneys’ fees, arbitration and administrative fees, and out-of-pocket expenses.',
        '8.2 Class Action Waiver. YOU AND SELARAI AGREE THAT EACH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. UNLESS BOTH PARTIES AGREE OTHERWISE IN WRITING, THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON\'S CLAIMS AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A REPRESENTATIVE OR CLASS PROCEEDING. IF THIS SPECIFIC PROVISION IS FOUND TO BE UNENFORCEABLE, THEN THE ENTIRETY OF THIS ARBITRATION PROVISION SHALL BE NULL AND VOID.',
      ],
    },
    {
      id: 'miscellaneous',
      title: 'MISCELLANEOUS',
      paragraphs: [
        'Authority. Each party represents that it has full authority to enter into these Terms and bind itself to its terms.',
        'Governing Law and Jurisdiction. These Terms will be governed by and construed in accordance with the laws of Delaware, without regard to its conflict of laws principles. You and SelarAI agree that any legal action or proceeding arising under or related in any way to these Terms will be brought in the state or federal courts of appropriate jurisdiction located in Wilmington, Delaware and venue will be proper in that court.',
        'Amendment; No Waiver. These Terms may not be amended except in a signed writing executed by authorized representatives of SelarAI and a user. No delay in exercising any right or remedy or failure to object will be a waiver of such right or remedy or any other right or remedy. A waiver on one occasion will not be a waiver of any right or remedy on any future occasion.',
        'Force Majeure. Except for payment obligations, neither Party will be responsible for failure or delay of performance if caused by: an act of war, hostility, or sabotage; act of God; electrical, internet, or telecommunication outage not caused by the obligated party; government restrictions; pandemic; or other event outside the reasonable control of the obligated party. Each party will use reasonable efforts to mitigate the effect of a force majeure event.',
        'Relationship of the Parties. You and we agree that no joint venture, partnership, employment, or agency relationship exists between us.',
        'Compliance with Laws. We will comply with all applicable U.S. state and federal laws and international laws in our operation and our provision of the Services. We reserve the right to disclose any information as necessary to comply with legal obligations, including laws, regulations, legal processes, or government requests. You agree not to export, re-export, or otherwise transfer access to the Services to any country, entity, or individual prohibited by applicable export control laws or sanctions programs.',
        'Severability. If any provision of these Terms is found to be invalid or unenforceable by a court of competent jurisdiction, that provision will be replaced by a valid and enforceable provision that most closely reflects the intent of the original, and the remainder of these Terms will remain in full force and effect.',
        'Notices. If you need to contact us for legal purposes, you may do so by email at legal@selaraillc.com or through any contact method listed on our website or in our application. We may provide you with notices via email, in-app messaging, or through any contact information associated with your account. You are responsible for keeping your contact details up to date.',
        'Entire Agreement. These Terms, including our Privacy Policy, constitute the entire agreement between you and SelarAI regarding the Services. It supersedes all other prior and contemporaneous proposals, agreements, or understandings, whether oral, written, or electronic. We expressly object to and reject any additional or conflicting terms you propose. Our obligations are not contingent upon the delivery of any future functionality or features unless expressly agreed to in writing.',
        'Assignment. You may not assign or transfer these Terms, in whole or in part, without SelarAI’s prior written consent, and any attempt to do so without consent will be null and void. We may assign or transfer these Terms without restriction, including in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of our assets. Subject to the foregoing, these Terms will bind and inure to the benefit of the Parties and their respective permitted successors and assigns.',
        'No Third Party Beneficiaries. Except as expressly provided in these Terms, including with respect to Apple Inc. and its subsidiaries as third-party beneficiaries of certain provisions related to the iOS App, nothing in this Agreement is intended to or will confer upon any third party any right, benefit, or remedy of any nature whatsoever under or by reason of this Agreement.',
        'Contract for Services. These Terms are for the provision of Services and not a sale of goods. The Uniform Commercial Code (UCC), the Uniform Computer Information Transactions Act (UCITA), and the United Nations Convention on Contracts for the International Sale of Goods do not apply to these Terms.',
        'Survival. Any provisions that by their nature should survive termination or expiration of these Terms, including but not limited to terms relating to payment obligations, use of the Services, confidentiality, intellectual property, disclaimers, limitations of liability, indemnification, and miscellaneous shall survive.',
        'Interpretation. The headings used in these Terms are for convenience only and will not affect the interpretation of any provision. The words “including,” “such as,” and similar terms are to be construed without limitation. These Terms will not be construed against either party as the drafter.',
        '[End of Terms of Service]',
      ],
    },
  ],
};
